#!/bin/bash
STR_MONTH=$(LC_TIME=en_DK.UTF-8 date +%b)
STR_YEAR=$(LC_TIME=en_DK.UTF-8 date +%y)

openstack image create --container-format bare --disk-format raw  --file ./result/win19stru_grid.raw --private --property hw_firmware_type=uefi --property hw_disk_bus=virtio --property hw_rescue_device=disk --property hw_rescue_bus=virtio --property os_type=windows --property rdp_type=windows "Windows Server 2019 Standard RU Tesla Driver ${STR_MONTH} ${STR_YEAR}"
openstack image create --container-format bare --disk-format raw  --file ./result/win19sten_grid.raw --private --property hw_firmware_type=uefi --property hw_disk_bus=virtio --property hw_rescue_device=disk --property hw_rescue_bus=virtio --property os_type=windows --property rdp_type=windows "Windows Server 2019 Standard EN Tesla Driver ${STR_MONTH} ${STR_YEAR}"
openstack image create --container-format bare --disk-format raw  --file ./result/win19dcru_grid.raw --private --property hw_firmware_type=uefi --property hw_disk_bus=virtio --property hw_rescue_device=disk --property hw_rescue_bus=virtio --property os_type=windows --property rdp_type=windows "Windows Server 2019 Datacenter RU Tesla Driver ${STR_MONTH} ${STR_YEAR}"
openstack image create --container-format bare --disk-format raw  --file ./result/win19dcen_grid.raw --private --property hw_firmware_type=uefi --property hw_disk_bus=virtio --property hw_rescue_device=disk --property hw_rescue_bus=virtio --property os_type=windows --property rdp_type=windows "Windows Server 2019 Datacenter EN Tesla Driver ${STR_MONTH} ${STR_YEAR}"
openstack image create --container-format bare --disk-format raw  --file ./result/win22stru_grid.raw --private --property hw_firmware_type=uefi --property hw_disk_bus=virtio --property hw_rescue_device=disk --property hw_rescue_bus=virtio --property os_type=windows --property rdp_type=windows "Windows Server 2022 Standard RU Tesla Driver ${STR_MONTH} ${STR_YEAR}"
openstack image create --container-format bare --disk-format raw  --file ./result/win19dcru_grid.raw --private --property hw_firmware_type=uefi --property hw_disk_bus=virtio --property hw_rescue_device=disk --property hw_rescue_bus=virtio --property os_type=windows --property rdp_type=windows "Windows Server 2022 Datacenter RU Tesla Driver ${STR_MONTH} ${STR_YEAR}"

openstack image create --container-format bare --disk-format raw  --file ./result/win19stru_game.raw --private --property hw_firmware_type=uefi --property hw_disk_bus=virtio --property hw_rescue_device=disk --property hw_rescue_bus=virtio --property os_type=windows --property rdp_type=windows "Windows Server 2019 Standard RU GameReady Driver ${STR_MONTH} ${STR_YEAR}"
openstack image create --container-format bare --disk-format raw  --file ./result/win19sten_game.raw --private --property hw_firmware_type=uefi --property hw_disk_bus=virtio --property hw_rescue_device=disk --property hw_rescue_bus=virtio --property os_type=windows --property rdp_type=windows "Windows Server 2019 Standard EN GameReady Driver ${STR_MONTH} ${STR_YEAR}"
openstack image create --container-format bare --disk-format raw  --file ./result/win19dcru_game.raw --private --property hw_firmware_type=uefi --property hw_disk_bus=virtio --property hw_rescue_device=disk --property hw_rescue_bus=virtio --property os_type=windows --property rdp_type=windows "Windows Server 2019 Datacenter RU GameReady Driver ${STR_MONTH} ${STR_YEAR}"
openstack image create --container-format bare --disk-format raw  --file ./result/win19dcen_game.raw --private --property hw_firmware_type=uefi --property hw_disk_bus=virtio --property hw_rescue_device=disk --property hw_rescue_bus=virtio --property os_type=windows --property rdp_type=windows "Windows Server 2019 Datacenter EN GameReady Driver ${STR_MONTH} ${STR_YEAR}"
openstack image create --container-format bare --disk-format raw  --file ./result/win22stru_game.raw --private --property hw_firmware_type=uefi --property hw_disk_bus=virtio --property hw_rescue_device=disk --property hw_rescue_bus=virtio --property os_type=windows --property rdp_type=windows "Windows Server 2022 Standard RU GameReady Driver ${STR_MONTH} ${STR_YEAR}"
openstack image create --container-format bare --disk-format raw  --file ./result/win19dcru_game.raw --private --property hw_firmware_type=uefi --property hw_disk_bus=virtio --property hw_rescue_device=disk --property hw_rescue_bus=virtio --property os_type=windows --property rdp_type=windows "Windows Server 2022 Datacenter RU GameReady Driver ${STR_MONTH} ${STR_YEAR}"

